### ISSUE TITLE
Declare Rx and Tx pins in the sketch and not in the library

### ISSUE THREAD

**Issue by vittorioexp** [VittorioEsposito/Sim800l-master-revised#1]
I don't know how i can declare rx and tx pins in the sketch without editing the library every time. Any ideas?

**Comment by cristiansteib** [comment]
Yes, in some days i'll write a new feature, and i this    is going to be included

**Comment by vittorioexp** [comment]
@cristiansteib Thank you. Feel free to continue the revised version of the library, if you want. Recently i added some methods about sleep mode and functionality mode. I don't understand why there is 152 seconds time out in _readSerial() method. And can you please test this library? I'll buy the shield soon.
