### ISSUE TITLE
Sim800l does not work (power supply problem)

### ISSUE THREAD

**Issue by vonhuhieunghia** [VittorioEsposito/Sim800l-master-revised#15]
I've connected my arduino nano to sim800l in a correct order but the LED on sim800l didn't turn on, and also the sim800l was heated a little.
(I used a 12V-15A power source with a Module LM2596 to lower the voltage)
Please help me, thank you

**Comment by Byt3x** [comment]
The Sim800l needs 3.4-4.4 volts, otherwise it won't work
